<?php

namespace Database\Seeders;

use App\Models\Affectation;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AffectationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $affectations = [
            "ADJENGRE",
            "AFAGNAN",
            "AGBELOUVE",
            "AGBODRAFO",
            "AGOU",
            "AHEPE",
            "AKLAKOU",
            "AMLAME",
            "AMOU-OBLO",
            "ANEHO",
            "ANFOIN",
            "ANIE",
            "ATAKPAME-AGBONOU",
            "ATAKPAME-RP",
            "BADOU",
            "BAFILO",
            "BARKOISSI",
            "BASSAR",
            "BLITTA",
            "BOMBOUAKA",
            "CINKASSE",
            "DANYI-APEYEME",
            "DAPAONG",
            "DJARKPANGA",
            "DRO-CENTRALE",
            "DRO-GOLFE",
            "DRO-KARA",
            "DRO-MARITIME",
            "DRO-PLATEAUX",
            "DRO-SAVANES",
            "ELAVAGNON",
            "GANDO",
            "GLEI",
            "GUERIN-KOUKA",
            "HAHOTOE",
            "HIHEATRO",
            "KABOLI",
            "KABOU",
            "KANTE",
            "KARA-COFAC",
            "KARA-STADE",
            "KETAO",
            "KEVE",
            "KOUGNOHOU",
            "KOUSSOUNTOU",
            "KPALIME",
            "KPELE-ADETA",
            "KPELE-ELE",
            "LOME-ADAKPAME",
            "LOME-ADETICOPE",
            "LOME-ADIDOGOME",
            "LOME-AEROPORT",
            "LOME-AGBALEPEDOGAN",
            "LOME-AGOE-ADJOUGBA",
            "LOME-AGOE-ATCHANVE",
            "LOME-AGOE-FIOVI",
            "LOME-AGOENYIVE-ASSIYEYE",
            "LOME-AGOE-ZONGO",
            "LOME-AKODESSEWA",
            "LOME-AMADAHOME",
            "LOME-APEDOKOE",
            "LOME-ATIKOUME",
            "LOME-AVEDJI",
            "LOME-AVEPOZO",
            "LOME-AVIATION",
            "LOME-BAGUIDA",
            "LOME-BE",
            "LOME-CCPE",
            "LOME-CI",
            "LOME-CITE",
            "LOME-CNTP",
            "LOME-CSFN",
            "LOME-DAT",
            "LOME-DCE",
            "LOME-DCF",
            "LOME-DCG",
            "LOME-DCGBT",
            "LOME-DCM",
            "LOME-DCOF",
            "LOME-DCP",
            "LOME-DCR",
            "LOME-DEC",
            "LOME-DFC",
            "LOME-DG",
            "LOME-DIGA",
            "LOME-DIGA-CIG",
            "LOME-DJAGBLE",
            "LOME-DJIFA-KPOTA",
            "LOME-DOUMASSESSE",
            "LOME-DPAS",
            "LOME-DPL",
            "LOME-DQSP",
            "LOME-DRHP",
            "LOME-DT",
            "LOME-EMS",
            "LOME-FC",
            "LOME-GBONVIE",
            "LOME-HEDZRANAWE",
            "LOME-KEGUE",
            "LOME-KPOGAN",
            "LOME-LEGBASSITO",
            "LOME-NYEKONAKPOE",
            "LOME-PHILATELIE",
            "LOME-PORT",
            "LOME-RP",
            "LOME-SC",
            "LOME-SEGBE",
            "LOME-TELESSOU",
            "LOME-TOKOIN",
            "LOME-WUITI",
            "LOME-ZANGUERA",
            "LOME-ZOSSIME",
            "MANDOURI",
            "MANGO",
            "MISSION TOVE-AFIADEGNIGBAN",
            "NIAMTOUGOU",
            "NOEPE",
            "NOTSE",
            "PAGALA",
            "PAGOUDA",
            "PYA",
            "SOKODE-KPANGALAM",
            "SOKODE-RP",
            "SOTOUBOUA",
            "TABLIGBO",
            "TCHAMBA",
            "TOHOUN",
            "TSEVIE",
            "VOGAN"
        ];

        foreach($affectations as $affectation)
        {
            Affectation::firstOrCreate([
                "libelle" => $affectation
            ]);
        }
        
    }
}
